Fri Apr 28 08:55:31 AM CST 2023

diff --git a/flamegraph-gen b/flamegraph-gen
--- a/flamegraph-gen
+++ b/flamegraph-gen
@@ -1,7 +1,8 @@
 #!/bin/bash
 FG_SECONDS=$(date +%s)
-FG_SVG_FILE="$HOME/FLAMEGRAPH-GEN/perf-$FG_SECONDS.svg"
-FG_PERF_DATA="$HOME/FLAMEGRAPH-GEN/perf-$FG_SECONDS.data"
+FG_OUT="$HOME/NVIDIA_OUT/flamegraph-gen"
+FG_SVG_FILE="$FG_OUT/perf-$FG_SECONDS.svg"
+FG_PERF_DATA="$FG_OUT/perf-$FG_SECONDS.data"
 FG_PERF_RECORD_SYSTEM_WIDE=1
 FG_PERF_RECORD_PID=" -a "
 FG_PERF_RECORD_SECONDS=10
@@ -12,17 +13,16 @@ FG_SUDO="sudo"
 ## MAIN FUNC
 #############
 
+if [ -z "$1" ]: then
+    echo "Usage: flamegraph-gen [--perf-data FILE] [--pid PID]"
+    echo "    --perf-data FILE: perf generated data to parse (default is to generate a new record)"
+    echo "    --pid PID: record callstacks of PID only (default is system-wide recording)"
+    echo "    --sleep SEC: record for SEC seconds"
+    exit 1
+fi
+
 while [ -n "$1" ]; do
     case "$1" in
-        help)
-            echo "USAGE: flamegraph-gen [help] [--perf-data FILE] [--pid PID]"
-            echo "    help: shows this message"
-            echo "    --perf-data FILE: perf generated data to parse (default is to generate a new record)"
-            echo "    --pid PID: record callstacks of PID only (default is system-wide recording)"
-            echo "    --sleep SEC: record for SEC seconds"
-            exit 0
-        ;;
-
         --perf-data)
             shift
             FG_PERF_DATA="$1"
@@ -42,28 +42,27 @@ while [ -n "$1" ]; do
         ;;
 
         *)
-            echo "ERROR: UNKNOWN ARGUMENT: $1" > /dev/stderr
-            glamegraph-gen help
-            exit 1
+	    flamegraph-gen
+	    exit 1
         ;;
     esac
     shift
 done
 
 if [ ! -d "$FLAMEGRAPH" ]; then
-    echo "ERROR: FLAMEGRAPH PATH DOES NOT EXIST" > /dev/stderr
+    echo "Error: Flamegraph path is missing" > /dev/stderr
     exit 1
 fi
 
 if [ ! -f "$FG_PERF_DATA" ]; then
-    echo "RUN PERF RECORD:"
-    echo "   OUTPUT: $FG_PERF_DATA"
-    echo "    SLEEP: $FG_PERF_RECORD_SECONDS SECONDS"
+    echo "Run perf record:"
+    echo "   Output: $FG_PERF_DATA"
+    echo "    Sleep: $FG_PERF_RECORD_SECONDS SECONDS"
     echo "      PID: $([[ $FG_PERF_RECORD_SYSTEM_WIDE -ne 0 ]] && echo \"[SYSTEM WIDE]\" || echo \"$FG_PERF_RECORD_PID\")"
-    echo "    OTHER: $FG_PERF_RECORD_ARGS"
+    echo "    Other: $FG_PERF_RECORD_ARGS"
     echo ""
 
-    mkdir -p "$HOME/FLAMEGRAPH-GEN"
+    mkdir -p "$FG_OUT"
     $FG_SUDO perf record $FG_PERF_RECORD_PID $FG_PERF_RECORD_ARGS --output="$FG_PERF_DATA" -- sleep $FG_PERF_RECORD_SECONDS
 
     if [ ! -z "$FG_SUDO" ]; then
@@ -72,9 +71,9 @@ if [ ! -f "$FG_PERF_DATA" ]; then
 fi
 
 if [ -f "$FG_PERF_DATA" ]; then
-    echo "GENERATE FLAMEGRAPH SVG (ZOOM AND SEARCH):"
-    echo "    PERF DATA: $FG_PERF_DATA"
-    echo "     SVG FILE: $FG_SVG_FILE"
+    echo "Generate flamegraph SVG (Zoom and Search):"
+    echo "    Perf data: $FG_PERF_DATA"
+    echo "     SVG file: $FG_SVG_FILE"
     echo ""
     BASENAME=$(basename -- "$FG_PERF_DATA")
     
@@ -111,9 +110,9 @@ if [ -f "$FG_PERF_DATA" ]; then
     "$FLAMEGRAPH/flamegraph.pl" \
        "/tmp/$BASENAME.perf.folded.recursive" \
        > "$FG_SVG_FILE" || (
-           echo "ERROR: FAILED TO GENERATE SVG FILE" > /dev/stderr
+           echo "Error: Failed to generate SVG file" > /dev/stderr
        )
 else
-    echo "ERROR: PERF DATA FILE DOES NOT EXIST: $FG_PERF_DATA" > /dev/stderr
+    echo "Error: Perf data file is missing: $FG_PERF_DATA" > /dev/stderr
     exit 1
 fi
diff --git a/nvidia-build b/nvidia-build
--- a/nvidia-build
+++ b/nvidia-build
@@ -1,21 +1,21 @@
 #!/bin/bash
 NVBRANCH="sw/dev/gpu_drv/dev_a"
-NVBUILD_LOCK=/tmp/NVBUILD_LOCK
-NVBUILD_OUT="$HOME/NVIDIA-BUILD"
-NVBUILD_SO_FILES="$NVBUILD_OUT/NVBUILD_SO_FILES"
+NVBUILD_LOCK="/tmp/nvbuild.lock"
+NVBUILD_OUT="$HOME/NVIDIA-OUT/nvidia-build"
+NVBUILD_SO_FILES="$NVBUILD_OUT/nvmake.products"
 NVFLAG_BACKUP=0
 
-function nvidia-source-version() {
+function nvbuild-source-version() {
     echo `grep '^#define NV_VERSION_STRING' $P4ROOT/$NVBRANCH/drivers/common/inc/nvUnixVersion.h  | awk '{print $3}' | sed 's/"//g'`
 }
 
-function nvidia-backup() {
+function nvbuild-backup() {
     if [ "$NVFLAG_BACKUP" != "1" ]; then
         return
     fi
 
     if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
-        echo "USAGE: nvidia-backup [ARCH] [BUILD_TYPE] [IS_PPP:BOOL]" > /dev/stderr
+        echo "Usage: nvbuild-backup [ARCH] [BUILD_TYPE] [IS_PPP:BOOL]" > /dev/stderr
         return 1
     fi
 
@@ -23,7 +23,7 @@ function nvidia-backup() {
     BUILD_TYPE="$2"
     IS_PPP="$3"
     FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
-    VERSION=$(nvidia-source-version)
+    VERSION=$(nvbuild-source-version)
     ARCHNAME=$([ "$ARCH" = "amd64" ] && echo "x86_64" || echo "$ARCH")
     SUFFIX=$([ "$IS_PPP" = "1" ] && echo "" || echo "-internal")
     NICKNAME=$([ "$IS_PPP" = "1" ] && echo "-32compat" || echo "")
@@ -36,37 +36,37 @@ function nvidia-backup() {
     fi
     
     cp "$SRC_FILE" "$DST_FILE" && (
-        echo "NVIDIA BACKUP: NVIDIA-$FOLDER-$VERSION$SUFFIX$NICKNAME.run"
+        echo "Create: NVIDIA-$FOLDER-$VERSION$SUFFIX$NICKNAME.run"
     ) 
     
     ln -s -f "$DST_FILE" "$NVBUILD_OUT/LAST_BUILD"
 }
 
-function nvidia-nvmake() {
+function nvbuild-nvmake() {
     ARCH="$1"
     BUILD_TYPE="$2"
     MODULE="$3"
     IS_PPP=0
     CWD_BACKUP="`pwd`"
-    mkdir -p "$HOME/NVIDIA-BUILD"
+    mkdir -p "$NVBUILD_OUT"
 
     if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
-        echo "USAGE: nvidia-nvmake [ARCH] [BUILD_TYPE] [MODULE]" > /dev/stderr
+        echo "Usage: nvbuild-nvmake [ARCH] [BUILD_TYPE] [MODULE]" > /dev/stderr
         return 1
     fi
 
     if [ -f "$NVBUILD_LOCK" ]; then
-        echo "ERROR: FILE $NVBUILD_LOCK EXISTS" > /dev/stderr
+        echo "Error: Lock $NVBUILD_LOCK exist" > /dev/stderr
         return 1
     fi
 
     if [ -z "$P4ROOT" ]; then
-        echo "ERROR: P4ROOT IS NOT DEFINED" > /dev/stderr
+        echo "Error: P4ROOT is missing" > /dev/stderr
         return 1
     fi
 
     if [ -z "$NVBRANCH" ]; then
-        echo "ERROR: NVBRANCH IS NOT DEFINED" > /dev/stderr
+        echo "Error: NVBRANCH is missing" > /dev/stderr
         return 1
     fi
 
@@ -95,16 +95,16 @@ function nvidia-nvmake() {
         ;;
 
         *)
-            echo "ERROR: MODULE \"$1\" IS NOT SUPPORTED" > /dev/stderr
+            echo "Error: Module \"$1\" is not supported" > /dev/stderr
             return 1
         ;;
     esac
 
     SECONDS=0
-    STDOUT_FILE="$NVBUILD_OUT/NVMAKE_STDOUT"
-    STDERR_FILE="$NVBUILD_OUT/NVMAKE_STDERR"
+    STDOUT_FILE="$NVBUILD_OUT/nvmake.stdout"
+    STDERR_FILE="$NVBUILD_OUT/nvmake.stderr"
 
-    echo "NVIDIA NVMAKE: linux $ARCH $BUILD_TYPE $MODULE"
+    echo "NVMake: linux $ARCH $BUILD_TYPE $MODULE"
     echo "`date +%s`" > "$NVBUILD_LOCK"
 
     if [ "$(stat -c '%U' $P4ROOT/sw/misc/linux/unix-build)" != "root" ]; then
@@ -138,7 +138,7 @@ function nvidia-nvmake() {
         ERRORCODE=1 
     )
 
-    echo "NVIDIA NVMAKE: TIME COST: [$(expr $SECONDS / 60) MINS]"
+    echo "NVMake: Time cost: [$(expr $SECONDS / 60) mins]"
     echo ""
 
     rm -rf "$NVBUILD_LOCK"
@@ -147,16 +147,17 @@ function nvidia-nvmake() {
     return $ERRORCODE
 }
 
+## MAIN
 
-
-
-
-
-
-
-#############
-## MAIN FUNC
-#############
+if [ -z "$1" ]; then
+    echo "Usage: nvidia-build [MODULE] [ARCH] [BUILD_TYPE] [ppp|sweep] [-b|--backup]"
+    echo "  e.g. nvidia-build sweep"
+    echo "  e.g. nvidia-build amd64 release -b"
+    echo "  e.g. nvidia-build amd64 release develop -b"
+    echo "  e.g. nvidia-build ppp -b"
+    echo "  e.g. nvidia-build ppp release develop -b"
+    exit 1
+fi
 
 ARCHS=""
 BUILD_TYPES=""
@@ -164,11 +165,6 @@ MODULES=""
 
 while [ -n "$1" ]; do
     case "$1" in
-        help)
-            echo "USAGE: nvidia-build [help] [ARCH] [BUILD_TYPE] [ppp] [sweep] [--backup] [--install]"
-            exit 0
-        ;;
-
         -b|--backup)
             NVFLAG_BACKUP=1
         ;;
@@ -210,8 +206,8 @@ while [ -n "$1" ]; do
         ;;
     
         *)
-            echo "ERROR: UNKNOWN ARGUMENT: $1" > /dev/stderr
-            nvidia-build help
+            echo "Error: Unknown argument: $1" > /dev/stderr
+            nvidia-build
             exit 1
         ;;
     esac
@@ -234,12 +230,13 @@ for ARCH in $ARCHS; do
     for BUILD_TYPE in $BUILD_TYPES; do
         for MODULE in $MODULES; do
             if [ "$MODULE" = "ppp" ]; then
-                nvidia-nvmake amd64 $BUILD_TYPE dist &&
-                nvidia-nvmake x86   $BUILD_TYPE dist &&
-                nvidia-nvmake amd64 $BUILD_TYPE ppp
+                nvbuild-nvmake amd64 $BUILD_TYPE dist &&
+                nvbuild-nvmake x86   $BUILD_TYPE dist &&
+                nvbuild-nvmake amd64 $BUILD_TYPE ppp
             else
-                nvidia-nvmake $ARCH $BUILD_TYPE $MODULE
+                nvbuild-nvmake $ARCH $BUILD_TYPE $MODULE
             fi
         done 
     done
 done
+
diff --git a/nvidia-install b/nvidia-install
--- a/nvidia-install
+++ b/nvidia-install
@@ -4,18 +4,21 @@ NVBRANCH="sw/dev/gpu_drv/dev_a"
 function dist-install() {
     INSTALLER=$([ "$1" = "" ] && echo "$HOME/NVIDIA-BUILD/LAST_BUILD" || echo "$1")
     if [ ! -f "$INSTALLER" ]; then
-        echo "ERROR: INSTALLER IS MISSING: $INSTALLER" > /dev/stderr
+        echo "Error: Installer is missing: $INSTALLER" > /dev/stderr
         return 1
     fi
 
     sudo chmod +x "$INSTALLER"
 
-    echo "NVIDIA INSTALL: $INSTALLER"
+    echo "Install NVIDIA Drivers: $INSTALLER"
     who am i > /dev/null && (
         sudo systemctl isolate multi-user
         sudo "$INSTALLER" -sb
         sudo systemctl isolate graphical
-    ) || echo "ERROR: YOU CAN ONLY RUN INSTALLER ON SSH" > /dev/stderr 
+    ) || (
+    	echo "Error: You can only run NVIDIA installer through SSH" > /dev/stderr
+        return 1
+    )	
 }
 
 function nvidia-source-version() {
@@ -24,7 +27,7 @@ function nvidia-source-version() {
 
 function nvidia-version-installed() {
     if [ "$1" = "" ]; then
-        echo "USAGE: nvidia-version-installed <ARCH>" > /dev/stderr
+        echo "Usage: nvidia-version-installed <ARCH>" > /dev/stderr
         return 1
     fi
 
@@ -38,14 +41,14 @@ function nvidia-version-installed() {
     if [ -f "/usr/lib/$ARCHNAME-linux-gnu/libnvidia-glvkspirv.so.$VERSION" ]; then
         echo "$VERSION"
     else
-        echo "ERROR: FAILED TO PARSE NVIDIA VERSION INSTALLED: $VERSION" > /dev/stderr
+        echo "Error: Failed to parse NVIDIA version installed: $VERSION" > /dev/stderr
         return 1
     fi
 }
 
 function module-install() {
     if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
-        echo "USAGE: module-install [MODULE] [ARCH] [BUILD_TYPE]" > /dev/stderr
+        echo "Usage: module-install [MODULE] [ARCH] [BUILD_TYPE]" > /dev/stderr
         return 1
     fi
 
@@ -55,11 +58,11 @@ function module-install() {
     FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
 
     if [ "$(nvidia-source-version)" != "$(nvidia-version-installed $ARCH)" ]; then  
-        echo "ERROR: \"SOURCE VERSION [$(nvidia-source-version)]\" != \"INSTALLED VERSION [$(nvidia-version-installed $ARCH)]\"" > /dev/stderr
+        echo "Error: \"Source Version [$(nvidia-source-version)]\" != \"Installed Version [$(nvidia-version-installed $ARCH)]\"" > /dev/stderr
         return 1
     fi
 
-    echo "NVIDIA INSTALL: $MODULE $ARCH $BUILD_TYPE"
+    echo "Install NVIDIA Module: $MODULE $ARCH $BUILD_TYPE"
     case "$MODULE" in
         opengl)
             FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
@@ -75,15 +78,15 @@ function module-install() {
                 fi
                 sudo cp -f "$OUTDIR/$BASENAME" "$TARGETNAME"
             else
-                echo "ERROR: $TARGETNAME IS MISSING" > /dev/stderr
+                echo "Error: $TARGETNAME is missing" > /dev/stderr
                 return 1
             fi
 
-            echo "BACKUP & UPDATE: $TARGETNAME"
+            echo "Backup & Update: $TARGETNAME"
         ;;
 
         *)
-            echo "ERROR: MODULE \"$MODULE\" IS NOT SUPPORTED" > /dev/stderr
+            echo "Error: Module \"$MODULE\" is not supported" > /dev/stderr
             return 1
         ;;
     esac 
@@ -91,7 +94,7 @@ function module-install() {
 
 function module-revert() {
     if [ "$1" = "" ]; then
-        echo "USAGE: module-revert [ARCH]" > /dev/stderr
+        echo "Usage: module-revert [ARCH]" > /dev/stderr
         return 1
     fi
 
@@ -101,14 +104,15 @@ function module-revert() {
 
     for FILE in `ls $FOLDER/*.backup`; do
         sudo mv -f "$FILE" "${FILE%.*}"
-        echo "REVERTED: ${FILE%.*}"
+        echo "Reverted: ${FILE%.*}"
     done
 }
 
 if [ "$1" = "" ]; then
-    echo "USAGE 1: nvidia-install <INSTALLER_PATH>"
-    echo "USAGE 2: nvidia-install <MODULE> <ARCH> <BUILD_TYPE>"
-    echo "USAGE 3: nvidia-install <-r|--revert> <ARCH>"
+    echo "Usage: nvidia-install [OPTIONS]"
+    echo "  e.g. nvidia-install <INSTALLER_PATH>"
+    echo "  e.g. nvidia-install <MODULE> <ARCH> <BUILD_TYPE>"
+    echo "  e.g. nvidia-install <-r|--revert> <ARCH>"
     exit 1
 fi
 
@@ -131,10 +135,11 @@ while [ -n "$1" ]; do
                 dist-install "$1"
                 break
             else
-                echo "ERROR: INSTALLER IS MISSING: $1" > /dev/stderr
+                echo "Error: NVIDIA installer is missing: $1" > /dev/stderr
                 exit 1
             fi
         ;;
     esac
     shift
 done
+
diff --git a/picv-gen b/picv-gen
--- a/picv-gen
+++ b/picv-gen
@@ -1,24 +1,30 @@
 #!/bin/bash
 
 if [ -z "$1" ]; then
-    echo "ERROR: PLEASE PROVIDE APPLICATION TO RUN AND CAPTURE" > /dev/stderr
+    echo "Error: Application to capture is missing" > /dev/stderr
+    exit 1
+fi
+
+if [ ! -d "$PIC_V" ]; then
+    echo "Error: PIC_V is missing" > /dev/stderr
     exit 1
 fi
 
 # Launch pic-v if it's not running
-pgrep -x pic-v >/dev/null && echo "PIC-V IS RUNNING..." || (
-    gnome-terminal -- bash -c "cd $HOME/NVIDIA/PIC-V && ./pic-v || read -p \"PRESS ANY KEY TO CONTINUE...\""
+pgrep -x pic-v >/dev/null && echo "PIC-V is running..." || (
+    gnome-terminal -- bash -c "cd $PIC_V && ./pic-v || read -p \"Press any key to continue...\""
     sleep 3
 )
 
 # Launch game in current terminal 
-cd $HOME/NVIDIA/PIC-V
+cd $PIC_V
 source setup-env.sh
 "$@" && (
     # Launch http server if it's not running
-    ps aux | grep "[p]ython3 -m http.server" && echo "PIC-V HTTP SERVER IS RUNNING..." || (
-        gnome-terminal -- bash -c "cd $HOME/NVIDIA/PIC-V/PerfInspector/output && ./launch-py3-server.sh || read -p \"PRESS ANY KEY TO CONTINUE...\""
+    ps aux | grep "[p]ython3 -m http.server" && echo "PIC-V HTTP server is running..." || (
+        gnome-terminal -- bash -c "cd $PIC_V/PerfInspector/output && ./launch-py3-server.sh || read -p \"Press any key to continue...\""
         sleep 1
     )
     chromium "http://localhost:8000/"
 )
+
diff --git a/talos-principle-in-pts b/talos-principle-in-pts
--- a/talos-principle-in-pts
+++ b/talos-principle-in-pts
@@ -4,12 +4,12 @@
 
 # Launch steam if it's not currently running
 pgrep -x steam >/dev/null && echo "STEAM IS RUNNING..." || (
-    gnome-terminal -- bash -c "steam || echo \"$(date)\" >> $HOME/FAILED_TO_START_STEAM"
+    gnome-terminal -- bash -c "steam || echo \"$(date)\" >> $HOME/NVIDIA-OUT/FAILED-TO-START-STEAM"
     sleep 15
 )
 
 if ! [[ -f "$HOME/.steam/steam/steamapps/common/The Talos Principle/Bin/x64/Talos" ]]; then
-    echo "INSTALL Talos Principle IN STEAM'S WINDOW AND TRY AGAIN"
+    echo "Install \"Talos Principle\" in Steam's window and try again"
     exit 1
 fi
 
diff --git a/zhujie b/zhujie
--- a/zhujie
+++ b/zhujie
@@ -1,8 +1,21 @@
 #!/bin/bash
 NVIDIA_BIN_URL="https://github.com/wanlizhu/NVIDIA_BIN.git"
 
-function devenv-init() {
-    # GNOME 
+function user-cancel() {
+    echo ""
+    popd > /dev/null
+    exit 0
+}
+
+function nvidia-packages-init() { 
+    # Git
+    sudo apt install git -y
+    sudo apt install gh -y # Use `gh auth login` to store GitHub credential locally
+    sudo git config --global user.email wanlizhu@hotmail.com
+    sudo git config --global user.name "Wanli Zhu"
+    gh auth login
+    
+    # GNOME
     gsettings set org.gnome.desktop.screensaver lock-enabled false
     gsettings set org.gnome.desktop.screensaver lock-delay 0
     gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false
@@ -17,13 +30,6 @@ function devenv-init() {
         sudo sh -c "echo -1 > /proc/sys/kernel/perf_event_paranoid"
         sudo echo "kernel.perf_event_paranoid = -1" >> /etc/sysctl.conf
     fi
-
-    # Git
-    sudo apt install git -y
-    sudo apt install gh -y # Use `gh auth login` to store GitHub credential locally
-    sudo git config --global user.email wanlizhu@hotmail.com
-    sudo git config --global user.name "Wanli Zhu"
-    # gh auth login
     
     # Tools
     sudo apt install openssh-server -y
@@ -56,7 +62,12 @@ function devenv-init() {
     
     # Simu mouse and key actions
     sudo apt install -y xdotool
-    
+
+    # Zero Tier
+    curl -s https://install.zerotier.com | sudo bash
+    sudo systemctl enable zerotier-one.service
+    sudo zerotier-cli join db64858fed3b37c1
+
     # CPolar
     curl -L https://www.cpolar.com/static/downloads/install-release-cpolar.sh | sudo bash
     cpolar authtoken NjgyZGY0N2UtY2Q0NS00NjExLWJmMTItNDU2OTNkNmY3YWQ5
@@ -64,35 +75,29 @@ function devenv-init() {
     sudo systemctl start cpolar
 }
 
-function user-cancel() {
-    echo ""
-    popd > /dev/null
-    exit 0
-}
-
-function devenv-pull() {
-    if [ ! -d "$HOME/NVIDIA/BIN" ]; then
-        echo "ERROR: $HOME/NVIDIA/BIN IS MISSING"
+function nvidia-bin-pull() {
+    if [ ! -d "$HOME/NVIDIA/bin" ]; then
+        echo "Error: $HOME/NVIDIA/bin is missing"
         exit 1
     fi
     
-    pushd "$HOME/NVIDIA/BIN" > /dev/null
+    pushd "$HOME/NVIDIA/bin" > /dev/null
     git pull $NVIDIA_BIN_URL master
     popd > /dev/null 
 }
 
-function devenv-push() {
-    if [ ! -d "$HOME/NVIDIA/BIN" ]; then
-        echo "ERROR: $HOME/NVIDIA/BIN IS MISSING"
+function nvidia-bin-push() {
+    if [ ! -d "$HOME/NVIDIA/bin" ]; then
+        echo "Error: $HOME/NVIDIA/bin is missing"
         exit 1
     fi
     
-    pushd "$HOME/NVIDIA/BIN" > /dev/null
+    pushd "$HOME/NVIDIA/bin" > /dev/null
     du -sh * | sort -rh
     echo ""
 
     trap user-cancel INT
-    read -r -n 1 -p "PRESS [ENTER] TO CONTINUE OR CTRL-C TO CANCEL: "
+    read -r -n 1 -p "Press [ENTER] to continue or CTRL-C to cancel: "
     echo ""
     
     git add .
@@ -101,38 +106,28 @@ function devenv-push() {
     popd > /dev/null
 }
 
-# function devenv-zerotier-join() {
-#     curl -s https://install.zerotier.com | sudo bash
-#     sudo systemctl enable zerotier-one.service
-#     sudo zerotier-cli join db64858fed3b37c1
-# }
+if [ -z "$1" ]; then
+    echo "Usage: zhujie [init] [pull] [push]"
+    exit 1
+fi
 
 while [ -n "$1" ]; do
     case "$1" in
-        help)
-            echo "USAGE: devenv [help] [init] [pull] [push]"
-            exit 0
-        ;;
-    
         init)
-            devenv-init
+            nvidia-packages-init
         ;;
         
         pull)
-            devenv-pull
+            nvidia-bin-pull
         ;;
         
         push)
-            devenv-push
-        ;;
-        
-        autostart)
-            devenv-autostart
+            nvidia-bin-push
         ;;
         
         *)
-            echo "ERROR: UNKNOWN ARGUMENT: $1" > /dev/stderr
-            devenv help
+	    zhujie
+	    exit 1
         ;;
     esac
     shift
