Fri May 26 11:16:01 CST 2023

diff --git a/zhujie b/zhujie
--- a/zhujie
+++ b/zhujie
@@ -264,13 +264,11 @@ function nvmake() {
     linux \
     $ARCH \
     $BUILD_TYPE \
-    $MODULE \
-    1> /tmp/zhujie-nvmake-Linux-$MODULE-$ARCH-$BUILD_TYPE.log \
-    2> /tmp/zhujie-nvmake-Linux-$MODULE-$ARCH-$BUILD_TYPE.error && (
+    $MODULE | tee /tmp/zhujie-nvmake-Linux-$MODULE-$ARCH-$BUILD_TYPE.log && (
         echo "NVMake: $(expr $SECONDS / 60) mins"
         popd > /dev/null 
     ) || (
-        grep -E -i -w "fatal|error|errors|critical|failed|: \*\*\*" /tmp/zhujie-nvmake-Linux-$MODULE-$ARCH-$BUILD_TYPE.error;
+        grep -E -i -w "fatal|error|errors|critical|failed|: \*\*\*" /tmp/zhujie-nvmake-Linux-$MODULE-$ARCH-$BUILD_TYPE.log;
         popd > /dev/null 
         exit 1
     )
@@ -718,14 +716,14 @@ function flamegraph() {
 
     echo -ne "Running perf record for $PERF_RECORD_SECONDS seconds\t"
     sudo perf record $PERF_RECORD_PID $PERF_RECORD_ARGS \
-        --output="$PERF_DATA" \
-        --sleep $PERF_RECORD_SECONDS \
-        2> /tmp/zhujie-$(basename $PERF_DATA).error \
-        && echo "[OK]" || (
-            echo "[FAILED]"
-            cat /tmp/zhujie-$(basename $PERF_DATA).error
-            exit 1
-        )
+    --output="$PERF_DATA" \
+    --sleep $PERF_RECORD_SECONDS \
+    2> /tmp/zhujie-$(basename $PERF_DATA).error \
+    && echo "[OK]" || (
+        echo "[FAILED]"
+        cat /tmp/zhujie-$(basename $PERF_DATA).error
+        exit 1
+    )
     sudo chmod 777 "$PERF_DATA"
 
     if [[ ! -f $PERF_DATA ]]; then
@@ -737,43 +735,43 @@ function flamegraph() {
     
     echo -ne "Running perf script\t"
     sudo perf script --input="$PERF_DATA" \
-        1> "/tmp/zhujie-$BASENAME.perf" \
-        2> "/tmp/zhujie-$BASENAME.perf.error" \
-        && echo "[OK]" || (
-            echo "[FAILED]"
-            cat "/tmp/zhujie-$BASENAME.perf.error"
-            exit 1
-        ) 
+    1> "/tmp/zhujie-$BASENAME.perf" \
+    2> "/tmp/zhujie-$BASENAME.perf.error" \
+    && echo "[OK]" || (
+        echo "[FAILED]"
+        cat "/tmp/zhujie-$BASENAME.perf.error"
+        exit 1
+    ) 
     
     echo -ne "Running stackcollapse-perf.pl\t"
     sudo stackcollapse-perf.pl "/tmp/zhujie-$BASENAME.perf" \
-        1> "/tmp/zhujie-$BASENAME.perf.folded" \
-        2> "/tmp/zhujie-$BASENAME.perf.folded.error" \
-        && echo "[OK]" || (\
-            echo "[FAILED]"
-            cat "/tmp/zhujie-$BASENAME.perf.folded.error"
-            exit 1
-        )
+    1> "/tmp/zhujie-$BASENAME.perf.folded" \
+    2> "/tmp/zhujie-$BASENAME.perf.folded.error" \
+    && echo "[OK]" || (\
+        echo "[FAILED]"
+        cat "/tmp/zhujie-$BASENAME.perf.folded.error"
+        exit 1
+    )
     
     echo -ne "Running stackcollapse-recursive.pl\t"
     sudo stackcollapse-recursive.pl "/tmp/zhujie-$BASENAME.perf.folded" \
-        1> "/tmp/zhujie-$BASENAME.perf.folded.recursive" \
-        2> "/tmp/zhujie-$BASENAME.perf.folded.recursive.error" \
-        && echo "[OK]" || (\
-            echo "[FAILED]"
-            cat "/tmp/zhujie-$BASENAME.perf.folded.recursive.error"
-            exit 1
-        )
+    1> "/tmp/zhujie-$BASENAME.perf.folded.recursive" \
+    2> "/tmp/zhujie-$BASENAME.perf.folded.recursive.error" \
+    && echo "[OK]" || (\
+        echo "[FAILED]"
+        cat "/tmp/zhujie-$BASENAME.perf.folded.recursive.error"
+        exit 1
+    )
     
     echo -ne "Running flamegraph.pl\t"
     sudo flamegraph.pl "/tmp/zhujie-$BASENAME.perf.folded.recursive" \
-        1> "$SVG_FILE" \
-        2> "/tmp/zhujie-$BASENAME.perf.folded.recursive.error" \
-        && echo "[OK]" || (\
-            echo "[FAILED]"
-            cat "/tmp/zhujie-$BASENAME.perf.folded.recursive.error"
-            exit 1
-        )
+    1> "$SVG_FILE" \
+    2> "/tmp/zhujie-$BASENAME.perf.folded.recursive.error" \
+    && echo "[OK]" || (\
+        echo "[FAILED]"
+        cat "/tmp/zhujie-$BASENAME.perf.folded.recursive.error"
+        exit 1
+    )
 }
     
 function p4bisect() {
@@ -1151,7 +1149,7 @@ function talos() {
     
     pushd "$HOME/.steam/steam/steamapps/common/The Talos Principle/Bin/x64" > /dev/null
     rm -rf /tmp/zhujie-talos.fps
-    $TASKSET $TASKSET_OPTIONS $CPU_LIST ./Talos +gfx_strAPI VLK +gfx_pixResWidth $WIDTH +gfx_pixResHeight $HEIGHT +exec $HOME/.phoronix-test-suite/installed-tests/pts/talos-principle-1.2.1/talos-run-test.lua 1> /tmp/zhujie-talos.log 2> /tmp/zhujie-talos.error 
+    $TASKSET $TASKSET_OPTIONS $CPU_LIST ./Talos +gfx_strAPI VLK +gfx_pixResWidth $WIDTH +gfx_pixResHeight $HEIGHT +exec $HOME/.phoronix-test-suite/installed-tests/pts/talos-principle-1.2.1/talos-run-test.lua | tee /tmp/zhujie-talos.log 
     popd > /dev/null
     
     FPS=$(cat "/tmp/zhujie-talos.log" | grep "Average:" | tail -n1 | awk '{print $3}')
@@ -1160,7 +1158,6 @@ function talos() {
         echo "$FPS" >> /tmp/zhujie-talos.fps
     else
         cat /tmp/zhujie-talos.log
-        cat /tmp/zhujie-talos.error
         return 1
     fi
 }
@@ -1194,17 +1191,13 @@ function apex() {
     fi
     
     if [[ $DIRECT_CALL == 0 ]]; then
-        /mnt/linuxqa/nvt.sh DxvkApexLegends --traces Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF \
-        1> /tmp/zhujie-Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF.log \
-        2> /tmp/zhujie-Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF.error
+        /mnt/linuxqa/nvt.sh DxvkApexLegends --traces Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF | tee /tmp/zhujie-Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF.log 
         
         FPS=$(cat /tmp/zhujie-Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF.log | grep -o 'dxvk-v[0-9.]*-fps[[:blank:]]\+[0-9.]*' | awk '{print $2}')
         if [[ -n $FPS ]]; then
             echo "$FPS :: "
             echo "$FPS" >> $FPS_FILE
         else
-            cat /tmp/zhujie-Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF.log
-            cat /tmp/zhujie-Apex_Legends_Ultra_${RESOLUTION}_1xAA_16xAF.error
             return 1
         fi
     else
@@ -1227,15 +1220,13 @@ function apex() {
             TASKSET_OPTIONS=""
         fi
         
-        cd /root/nvt/tests/dxvk/run_dir; DISPLAY=:0.0 DXVK_HUD=full DXVK_LOG_LEVEL=none DXVK_STATE_CACHE=0 LD_LIBRARY_PATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib64:/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib:/mnt/linuxqa/nvtest/pynv_files/vulkan_loader/sdk-1.1.114/Linux_amd64:/mnt/linuxqa/nvtest/pynv_files/vkdevicechooser/Linux_amd64 LIBC_FATAL_STDERR_=1 NODEVICE_SELECT=1 PATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/files/bin:/root/NVIDIA_TOOLS:/root:/root/bin:/root/.local/bin:/root/NVIDIA_TOOLS:/root:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin PROTON_VR_RUNTIME=1 STEAM_COMPAT_DATA_PATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/prefix VK_ICD_FILENAMES=/etc/vulkan/icd.d/nvidia_icd.json VK_INSTANCE_LAYERS=VK_LAYER_AEJS_DeviceChooserLayer VK_LAYER_PATH=/mnt/linuxqa/nvtest/pynv_files/vulkan_loader/sdk-1.1.114/Linux_amd64/explicit_layer.d:/mnt/linuxqa/nvtest/pynv_files/vkdevicechooser VR_OVERRIDE=1 VULKAN_DEVICE_INDEX=0 WINEDEBUG=-all WINEDLLOVERRIDES='steam.exe=b;d3d11=n;d3d10core=n;dxgi=n;d3d11x_42=n;d3d11x_43=n;d3d9=n;nvcuda=b;' WINEDLLPATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib64/wine:/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib/wine WINEESYNC=1 WINEPREFIX=/root/nvt/tests/dxvk/experimental-7.0-20230201/prefix/pfx WINE_MONO_OVERRIDES='Microsoft.Xna.Framework.*,Gac=n' __GL_4718b=0x00000008 __GL_61807119=/root/nvt/log/loadmonitor/00057_run-in-soldier __GL_SHADER_DISK_CACHE=0 __GL_SYNC_TO_VBLANK=0  $TASKSET $TASKSET_OPTIONS $CPU_LIST /root/nvt/tests/dxvk/experimental-7.0-20230201/files/bin/wine /root/nvt/tests/dxvk/run_dir/r5apex.exe 1000 0 fps_log 1> /tmp/zhujie-Apex_Legends.log 2> /tmp/zhujie-Apex_Legends.error 
+        cd /root/nvt/tests/dxvk/run_dir; DISPLAY=:0.0 DXVK_HUD=full DXVK_LOG_LEVEL=none DXVK_STATE_CACHE=0 LD_LIBRARY_PATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib64:/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib:/mnt/linuxqa/nvtest/pynv_files/vulkan_loader/sdk-1.1.114/Linux_amd64:/mnt/linuxqa/nvtest/pynv_files/vkdevicechooser/Linux_amd64 LIBC_FATAL_STDERR_=1 NODEVICE_SELECT=1 PATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/files/bin:/root/NVIDIA_TOOLS:/root:/root/bin:/root/.local/bin:/root/NVIDIA_TOOLS:/root:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin PROTON_VR_RUNTIME=1 STEAM_COMPAT_DATA_PATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/prefix VK_ICD_FILENAMES=/etc/vulkan/icd.d/nvidia_icd.json VK_INSTANCE_LAYERS=VK_LAYER_AEJS_DeviceChooserLayer VK_LAYER_PATH=/mnt/linuxqa/nvtest/pynv_files/vulkan_loader/sdk-1.1.114/Linux_amd64/explicit_layer.d:/mnt/linuxqa/nvtest/pynv_files/vkdevicechooser VR_OVERRIDE=1 VULKAN_DEVICE_INDEX=0 WINEDEBUG=-all WINEDLLOVERRIDES='steam.exe=b;d3d11=n;d3d10core=n;dxgi=n;d3d11x_42=n;d3d11x_43=n;d3d9=n;nvcuda=b;' WINEDLLPATH=/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib64/wine:/root/nvt/tests/dxvk/experimental-7.0-20230201/files/lib/wine WINEESYNC=1 WINEPREFIX=/root/nvt/tests/dxvk/experimental-7.0-20230201/prefix/pfx WINE_MONO_OVERRIDES='Microsoft.Xna.Framework.*,Gac=n' __GL_4718b=0x00000008 __GL_61807119=/root/nvt/log/loadmonitor/00057_run-in-soldier __GL_SHADER_DISK_CACHE=0 __GL_SYNC_TO_VBLANK=0  $TASKSET $TASKSET_OPTIONS $CPU_LIST /root/nvt/tests/dxvk/experimental-7.0-20230201/files/bin/wine /root/nvt/tests/dxvk/run_dir/r5apex.exe 1000 0 fps_log | tee /tmp/zhujie-Apex_Legends.log 
         
         FPS=$(cat /tmp/zhujie-Apex_Legends.log | grep -o 'average FPS: [0-9.]*' | awk '{print $3}')
         if [[ -n $FPS ]]; then
             echo "$FPS :: "
             echo "$FPS" >> $FPS_FILE
         else
-            cat /tmp/zhujie-Apex_Legends.log
-            cat /tmp/zhujie-Apex_Legends.error
             return 1
         fi
     fi
@@ -1305,9 +1296,7 @@ function catia() {
     fi
         
     pushd $(get-viewperf-home) > /dev/null
-    $TASKSET $TASKSET_OPTIONS $CPU_LIST viewperf/bin/viewperf viewsets/catia/config/catia.xml -resolution $RESOLUTION \
-    1> /tmp/zhujie-catia_${RESOLUTION}.log \
-    2> /tmp/zhujie-catia_${RESOLUTION}.error 
+    $TASKSET $TASKSET_OPTIONS $CPU_LIST viewperf/bin/viewperf viewsets/catia/config/catia.xml -resolution $RESOLUTION | tee /tmp/zhujie-catia_${RESOLUTION}.log 
     popd > /dev/null
     
     FPS=$(cat /tmp/zhujie-catia_${RESOLUTION}.log | grep "<Composite Score=" | grep -o '".*"' | awk '{print substr($0, 2, length($0) - 2)}')
@@ -1315,8 +1304,6 @@ function catia() {
         echo "$FPS :: " 
         echo "$FPS" >> $HOME/zhujie-catia_${RESOLUTION}.fps
     else
-        cat /tmp/zhujie-catia_${RESOLUTION}.log
-        cat /tmp/zhujie-catia_${RESOLUTION}.error
         return 1
     fi
 }
@@ -1357,9 +1344,7 @@ function creo() {
     fi
         
     pushd $(get-viewperf-home) > /dev/null
-    $TASKSET $TASKSET_OPTIONS $CPU_LIST viewperf/bin/viewperf viewsets/creo/config/creo.xml -resolution $RESOLUTION \
-    1> /tmp/zhujie-creo_${RESOLUTION}.log \
-    2> /tmp/zhujie-creo_${RESOLUTION}.error 
+    $TASKSET $TASKSET_OPTIONS $CPU_LIST viewperf/bin/viewperf viewsets/creo/config/creo.xml -resolution $RESOLUTION | tee /tmp/zhujie-creo_${RESOLUTION}.log 
     popd > /dev/null
     
     FPS=$(cat /tmp/zhujie-creo_${RESOLUTION}.log | grep "<Composite Score=" | grep -o '".*"' | awk '{print substr($0, 2, length($0) - 2)}')
@@ -1367,8 +1352,6 @@ function creo() {
         echo "$FPS :: "
         echo "$FPS" >> $HOME/zhujie-creo_${RESOLUTION}.fps
     else
-        cat /tmp/zhujie-creo_${RESOLUTION}.log
-        cat /tmp/zhujie-creo_${RESOLUTION}.error
         return 1
     fi
 }
@@ -2115,11 +2098,10 @@ function average-fps() {
     for i in `seq 1 $LOOPS`; do
         echo -ne "Running $i out of $LOOPS iterations ... "
         
-        "$@" 1>/tmp/zhujie-$1.log 2>/tmp/zhujie-$1.error && (
+        "$@" | tee /tmp/zhujie-$1.log && (
             cat /tmp/zhujie-$1.log | grep "::" | awk -F '::' '{ print "FPS: " $1 }' | tee -a /tmp/zhujie-average-fps$SUFFIX
         ) || (
             cat /tmp/zhujie-$1.log
-            cat /tmp/zhujie-$1.error
         )
     done
     
