Wed May 10 06:29:58 PM CST 2023

diff --git a/zhujie b/zhujie
--- a/zhujie
+++ b/zhujie
@@ -632,6 +632,7 @@ function talos() {
 
     CWD_BAK="$(pwd)"
     cd "$HOME/.steam/steam/steamapps/common/The Talos Principle/Bin/x64"
+    rm -rf $HOME/zhujie-talos.log
     echo "Info: ./Talos 2560x1440 is running..."
     ./Talos +gfx_strAPI VLK +gfx_pixResWidth 2560 +gfx_pixResHeight 1440 +exec $HOME/.phoronix-test-suite/installed-tests/pts/talos-principle-1.2.1/talos-run-test.lua | tee $HOME/zhujie-talos.log
     cd "$CWD_BAK"
@@ -1227,7 +1228,10 @@ function vnc() {
     
     if [ ! -f "$HOME/.vnc/passwd" -a "$CMD" = "start" ]; then
         echo "Creating ~/.vnc/passwd file..."
-        vncpasswd
+        vncpasswd || (
+            echo "Error: can't generate VNC password at $HOME/.vnc/passwd, aborting..." > /dev/stderr
+            exit 1
+        )
     fi
     
     if [ ! -z "$VNCPORT" ]; then
