Tue May 23 12:09:27 CST 2023

diff --git a/zhujie b/zhujie
--- a/zhujie
+++ b/zhujie
@@ -901,6 +901,15 @@ function x0vnc() {
         VNCPORT=5900
     fi
     
+    if [[ ! -f $HOME/.vnc/passwd ]]; then
+        (echo '123456'; echo '123456'; echo 'n') | vncpasswd > /dev/null && (
+            echo "VNC password is 123456"
+        ) || (
+            echo "Error: failed to call vncpasswd" > /dev/stderr
+            exit 1
+        )
+    fi
+    
     while [[ -n $1 ]]; do
         case $1 in
             status)
@@ -920,6 +929,7 @@ function x0vnc() {
                 exit 1
             ;;
         esac
+        shift
     done
 }
     
@@ -935,6 +945,15 @@ function vnc() {
     
     if [[ -z $VNCPORT ]]; then
         VNCPORT=5900
+    fi
+    
+     if [[ ! -f $HOME/.vnc/passwd ]]; then
+        (echo '123456'; echo '123456'; echo 'n') | vncpasswd > /dev/null && (
+            echo "VNC password is 123456"
+        ) || (
+            echo "Error: failed to call vncpasswd" > /dev/stderr
+            exit 1
+        )
     fi
 
     while [[ -n $1 ]]; do
@@ -952,6 +971,7 @@ function vnc() {
                 vncserver -localhost no -PasswordFile $HOME/.vnc/passwd -rfbport $VNCPORT -geometry $GEOMETRY
             ;;
         esac
+        shift
     done
 }
     
