Fri May 26 01:58:50 CST 2023

diff --git a/zhujie b/zhujie
--- a/zhujie
+++ b/zhujie
@@ -2242,7 +2242,12 @@ function build-gcc() {
     fi
     
     pushd $HOME/gcc-src
-    git checkout releases/gcc-$VERSION
+    git checkout releases/gcc-$VERSION || (
+        echo "Error: releases/gcc-$VERSION doesn't exist" > /dev/stderr
+        popd
+        exit 1    
+    )
+    
     ./contrib/download_prerequisites
     mkdir build-objdir
     cd build-objdir
